"""Demo: AI-generated code tries to import a hallucinated npm package.

The Sentinel picks up the PR event, Analyst runs hallucination-check,
Auditor blocks the change, and Remediator drafts a comment.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

# Add project root to path for direct script execution
project_root = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(project_root / "src"))

from supplyguard.runtime.local_orchestrator import LocalOrchestrator


async def main() -> None:
    """Run the slopsquatting guard demo."""
    orchestrator = LocalOrchestrator()

    # Simulate a PR where AI-generated code imports a non-existent package.
    # "lodos" is a classic typosquat of "lodash".
    event = {
        "session_id": "demo-slopsquatting-001",
        "source": "github_pr",
        "repo_url": "https://github.com/acme/demo-app",
        "commit_sha": "deadbeef",
        "changes": [
            {
                "package_name": "lodos",
                "new_version": "^1.0.0",
                "is_new": True,
                "ecosystem": "npm",
                "context_text": "import { cloneDeep } from 'lodos'; // generated by Copilot",
            }
        ],
    }

    print("=" * 60)
    print("SupplyGuard Demo: Slopsquatting / Hallucination Detection")
    print("=" * 60)

    result = await orchestrator.run_guard(event)

    print("\nWorkflow result:")
    print(json.dumps(result, indent=2, default=str))

    await orchestrator.close()


if __name__ == "__main__":
    asyncio.run(main())
